### ISSUE TITLE
[DID Reference] REQUIREMENT: A capability is needed to Test If a DID Exists on the Ledger

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-resolution#24]
A capability is needed to `Test If a DID Exists on the Ledger` ...without having to incur the cost of constructing and returning a DID Document.

The DID Resolver Response should contain something like a simple Boolean (True/False) response ...and not a DID Document.

**Comment by peacekeeper** [comment]
I agree this seems like a good idea. It will probably be an optional feature for DID methods and resolvers.

**Comment by TomCJones** [comment]
this is a turning complete problem. Meaning that the only way to be sure a did is NOT there is to run the full chain. It would take less time only if there were a did that as active sometime in the recent past.  Which is also a "freshness" measure. Thus the return may as well return the date of last use.

**Comment by mwherman2000** [comment]
Closed in favor of https://github.com/w3c-ccg/did-resolution/issues/32

**Comment by mwherman2000** [comment]
Closed in favor of https://github.com/w3c-ccg/did-resolution/issues/32
