### ISSUE TITLE
[DID Reference] REQUIREMENT: Ability to query a DID Method's resolution capabilities

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-resolution#25]
With the possibility of there being many optional capabilities that are supported by a particular DID Method, we need some way to query, on a DID Method-by-DID Method basis, the list of capabilities that are supported by a particular DID Method.  Inspired by this example: https://github.com/w3c-ccg/did-resolution/issues/24

This is a simple related specification/protocol I wrote for the NEO Blockchain: https://github.com/neo-project/proposals/blob/master/nep-10.mediawiki

**Comment by peacekeeper** [comment]
Agreed, seems to be another useful capability. Like #27 I wonder a bit if this is in scope for the DID Resolution spec, or rather an implementation-specific feature that doesn't really need to be standardized. I could imagine it either way, let's discuss.

**Comment by mwherman2000** [comment]
Closed in favor of https://github.com/w3c-ccg/did-resolution/issues/32
