### ISSUE TITLE
[DID Reference] REQUIREMENT: Ability to `ping` a DID Resolver to see if it is alive and responsive

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/did-resolution#27]
Ability to `ping` a DID Resolver to see if it is alive and responsive.

Sample request: `did:?ping`

Response: A DID Resolver Response containing a JSON subelement containing a current TOD timestamp in milliseconds.

**Comment by peacekeeper** [comment]
Thanks @mwherman2000 this seems like a useful feature. I'm not sure if this should be part of the DID Resolution spec, since it's not directly related to the resolution process itself. Instead it could be an implementation-specific feature. But let's discuss.

**Comment by mwherman2000** [comment]
I think we need to revisit and rework the Purpose of the DID Resolution spec this week - expecially wrt scope.

I'm perhaps thinking more broadly as the DID Resolution spec being the "API" for a DID Resolver ...which embraces then extends actual DID resolution.

**Comment by TomCJones** [comment]
it would be much better if a real json object were returned - same with error - in fact any invalid request should be a fine ping.

**Comment by mwherman2000** [comment]
Closed in favor of https://github.com/w3c-ccg/did-resolution/issues/32

**Comment by mwherman2000** [comment]
Closed in favor of https://github.com/w3c-ccg/did-resolution/issues/32
