### ISSUE TITLE
Change key terms to lowercase

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-resolution#48]
In the DID spec, we changed all defined terms to lowercase (e.g. DID Document -> DID document, see https://github.com/w3c/did-spec/pull/73). We should do the same here for the DID Resolution spec.

**Comment by peacekeeper** [comment]
BTW this would be a good opportunity as an initial PR for anyone who would like to start contributing to this spec!

**Comment by mskuybeda** [comment]
May I give it a try?

**Comment by mskuybeda** [comment]
Update. I did a pull request, please review.

**Comment by peacekeeper** [comment]
Thanks for doing this! Just left a revew on the PR.
