### ISSUE TITLE
What's the expected behavior for a DID Document that contains the same id property for publicKeys?

### ISSUE THREAD

**Issue by kdenhartog** [w3c-ccg/did-resolution#65]
Given the following DID Document, what's the expected result from the dereference function?

```json
  {
    "@context": [
      "https://www.w3.org/ns/did/v1",
      "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id": "did:example:123",
    "verificationMethod": [
      {
        "id": "did:example:123#publicKey",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:example:123",
        "publicKeyMultibase": "zAKJP3f7BD6W4iWEQ9jwndVTCBq8ua2Utt8EEjJ6Vxsf"
      },
      {
        "id": "#publicKey",
        "type": "Ed25519VerificationKey2020",
        "controller": "did:example:123",
        "publicKeyMultibase": "differentPublicKeyExample....."
      }
    ],
}
```

`dereference("did:example:123#publicKey", {"accept": "application/did+ld+json"})` => ????

**Comment by peacekeeper** [comment]
Good question, I think that's basically a question for JSON-LD itself and is not really specific to DIDs or DID documents or DID URL dereferencing.

The JSON-LD spec at https://w3c.github.io/json-ld-syntax/#application-ld-json says this:

> Fragment identifiers used with application/ld+json are treated as in RDF syntaxes, as per RDF 1.1 Concepts and Abstract Syntax [RDF11-CONCEPTS].

But this isn't very helpful, is it?

My assumption has been that the dereferencer picks the JSON object with the matching `id`, and also adds all applicable contexts, i.e. the result in your specific example would be:

```
  {
  	"@context": [
  		"https://www.w3.org/ns/did/v1",
  		"https://w3id.org/security/suites/ed25519-2020/v1"
  	],
  	"id": "did:example:123#publicKey",
  	"type": "Ed25519VerificationKey2020",
  	"controller": "did:example:123",
  	"publicKeyMultibase": "zAKJP3f7BD6W4iWEQ9jwndVTCBq8ua2Utt8EEjJ6Vxsf"
  }
```

But this isn't really documented anywhere; and for `application/did+json` the use of the fragment is completely undefined (probably assumed to be the same as for `application/did+ld+json`).

**Comment by kdenhartog** [comment]
In JSON-LD's case it appears like it's treating them as nodes that can be merged (I think that's the right way to describe what's happening when the properties are being merged in the output of the frame). Here's a [json-ld playground example](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fdid%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fsuites%2Fed25519-2020%2Fv1%22%2C%7B%22%40base%22%3A%22did%3Aexample%3A123%22%7D%5D%2C%22id%22%3A%22did%3Aexample%3A123%22%2C%22verificationMethod%22%3A%5B%7B%22id%22%3A%22did%3Aexample%3A123%23publicKey%22%2C%22type%22%3A%22Ed25519VerificationKey2020%22%2C%22controller%22%3A%22did%3Aexample%3A123%22%2C%22publicKeyMultibase%22%3A%22zAKJP3f7BD6W4iWEQ9jwndVTCBq8ua2Utt8EEjJ6Vxsf%22%7D%2C%7B%22id%22%3A%22%23publicKey%22%2C%22type%22%3A%22Ed25519VerificationKey2020%22%2C%22controller%22%3A%22did%3Aexample%3A123%22%2C%22publicKeyMultibase%22%3A%22differentPublicKeyExample.....%22%7D%5D%7D&frame=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fdid%2Fv1%22%2C%22https%3A%2F%2Fw3id.org%2Fsecurity%2Fsuites%2Fed25519-2020%2Fv1%22%5D%2C%22%40base%22%3A%22did%3Aexample%3A123%22%2C%22verificationMethod%22%3A%7B%22%40id%22%3A%22did%3Aexample%3A123%23publicKey%22%7D%7D) to see what I mean.

**Comment by OR13** [comment]
> An id property MUST NOT match any other `@id` properties within the same DID Document. Seems good enough to cover it for now.

Probably should have been explicit:

> The Absolute DID URL of a verification relationship or service `id` must be unique and present only once in the did document.
