### ISSUE TITLE
methodNotSupported has no associated HTTP status code

### ISSUE THREAD

**Issue by aljones15** [w3c-ccg/did-resolution#72]
The spec states to throw the error and add it to the `didResolutionMetadata`, but unlike other errors we don't know the status code for it.

**Comment by peacekeeper** [comment]
I agree, this is missing. Do you have a suggestion? Maybe 400?

We should probably also define a "default" HTTP status code (400? 500?)  if the didResolutionMetadata contains any other error that is not explicitly mapped to an HTTP status code.

**Comment by aljones15** [comment]
Those are both issues I've been dealing with this week. I think a default of 500 sounds about right.

One possibility is this for `methodNotSupported`:

[406 Not Acceptable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406)
This response is sent when the web server, after performing [server-driven content negotiation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#server-driven_negotiation), doesn't find any content that conforms to the criteria given by the user agent.

As we were unable to find a driver that could resolve the did method given.

**Comment by peacekeeper** [comment]
I agree with 500 as default.

Regarding "methodNotSupported", I don't think 406 is right, since that's for content negotiation, and we're already mapping "representationNotSupported" to 406.

I think "methodNotSupported" should map to either 404 (since the DID is essentially "not found" by that resolver; kind of like asking for a path on a web server that doesn't exist), or 400 (meaning the client sent a bad request).

**Comment by aljones15** [comment]
`404` sounds better to me, but I'm not exactly an expect in this field.

**Comment by TallTed** [comment]
4xx don't feel right, as the user/client did nothing wrong in their request.  Rather, it's the server that doesn't know how to handle the client's properly-formed request -- and thus I think [`501`](https://www.rfc-editor.org/rfc/rfc9110.html#name-501-not-implemented) is the most correct.

> The `501 (Not Implemented)` status code indicates that _the server does not support the functionality required to fulfill the request_. 

Emphasis added in the quotation above.

**Comment by aljones15** [comment]
@peacekeeper `501` is not used currently and seems pertinent.

**Comment by peacekeeper** [comment]
I agree with `501`. Could you maybe review https://github.com/w3c-ccg/did-resolution/pull/73 and https://github.com/w3c-ccg/did-resolution/pull/74 ?

**Comment by aljones15** [comment]
closing as methodNotSupported is now associated with 501.
